<?php

/**
 * @file
 * Glossify module.
 */

/**
 * Implements hook_theme().
 */
function glossify_theme() {
  return [
    'glossify_tooltip' => [
      'variables' => [
        'word' => NULL,
        'tip' => NULL,
        'langcode' => NULL,
      ],
    ],
    'glossify_link' => [
      'variables' => [
        'word' => NULL,
        'tip' => NULL,
        'tipurl' => NULL,
      ],
    ],
  ];
}
