email_registration_username.settings:
  type: config_object
  label: 'Email registration username config'
  mapping:
    obfuscation_value:
      type: label
      label: 'User display name obfuscation value'
