<?php

/**
 * @file
 * Mailgun test module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function mailgun_test_form_mailgun_admin_settings_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Replace settings form validate with fake one.
  $index = array_search('::validateForm', $form['#validate']);
  $form['#validate'][$index] = 'mailgun_test_settings_form_validate';
}

/**
 * Overridden validate for test purposes.
 */
function mailgun_test_settings_form_validate($form, FormStateInterface $form_state) {
  if (($form_state->getValue('api_key_storage') == 'config'
    && $form_state->getValue('api_key') === 'key-1234567890workingabcdefghijklmno')
    || ($form_state->getValue('api_key_storage') == 'key'
    && \Drupal::service('key.repository')->getKey($form_state->getValue('api_key_key'))->getKeyValue() === 'key-1234567890workingabcdefghijklmno')

    ) {
    // Do nothing. It's just to emulate correct API key.
  }
  else {
    // Replace settings form validate with the real one.
    $index = array_search('mailgun_test_settings_form_validate', $form['#validate']);
    $form['#validate'][$index] = '::validateForm';
    \Drupal::formBuilder()->executeValidateHandlers($form, $form_state);
  }
}
